# BarberManager — SonarQube Configuration
sonar.projectKey=barbermanager
sonar.projectName=BarberManager
sonar.projectVersion=1.0

# Fontes a analisar
sonar.sources=src
sonar.inclusions=**/*.js,**/*.html,**/*.pas,**/*.dpr

# Servidor
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

# Exclusões
sonar.exclusions=**/node_modules/**,**/.git/**,**/Win32/**,**/Android/**,**/*.dcu,**/*.dproj,**/*.res,**/*.identcache
