unit View.Principal;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.TabControl,
  FMX.Layouts, FMX.Objects, FMX.Controls.Presentation, FMX.StdCtrls, FMX.Edit;

type
  TFrmPrincipal = class(TForm)
    TabControlPrincipal: TTabControl;
    TabLogin: TTabItem;
    TabNovaConta: TTabItem;
    lytPrincipalLogin: TLayout;
    rectLogoApp: TRectangle;
    lytLogoCentralizado: TLayout;
    lblTituloApp: TLabel;
    rectFundoTabLogin: TRectangle;
    lblSubTituloApp: TLabel;
    lytCampoEmail: TLayout;
    lblEmail: TLabel;
    rectFundoEmail: TRectangle;
    edtEmail: TEdit;
    lytCampoSenha: TLayout;
    lblSenha: TLabel;
    rectFundoSenha: TRectangle;
    edtSenha: TEdit;
    rectBtnEntrar: TRectangle;
    lblBtnEntrar: TLabel;
    btnAcessarLogin: TSpeedButton;
    rectBtnNovaConta: TRectangle;
    lblBtnNovaConta: TLabel;
    btnNovaConta: TSpeedButton;
    rectFundoTabNovaConta: TRectangle;
    scrollNovaConta: TVertScrollBox;
    lytVoltar: TLayout;
    lblVoltar: TLabel;
    lytLogoCentralizadoNovaConta: TLayout;
    Rectangle1: TRectangle;
    Label1: TLabel;
    Label2: TLabel;
    lytCampoConfirma: TLayout;
    lblConfirma: TLabel;
    Rectangle2: TRectangle;
    edtConfirmarSenha: TEdit;
    lytCampoSenhaCad: TLayout;
    lblSenhaCad: TLabel;
    Rectangle3: TRectangle;
    edtSenhaCadastro: TEdit;
    lytCampoEmailCad: TLayout;
    lblEmailCad: TLabel;
    Rectangle4: TRectangle;
    edtEmailCadastro: TEdit;
    lytCampoNome: TLayout;
    lblNome: TLabel;
    Rectangle5: TRectangle;
    edtNomeCadastro: TEdit;
    lytTermos: TLayout;
    chkTermos: TCheckBox;
    Label3: TLabel;
    rectBtnCadastrar: TRectangle;
    Label4: TLabel;
    SpeedButton1: TSpeedButton;
    lytRodapeCadastro: TLayout;
    lblJaTenhoConta: TLabel;
    tabClienteHome: TTabItem;
    rectFundoHome: TRectangle;
    rectMenuInferior: TRectangle;
    GridPanelLayout1: TGridPanelLayout;
    lytMenuInicio: TLayout;
    lytMenuAgenda: TLayout;
    lytMenuCarrinho: TLayout;
    lytMenuPerfil: TLayout;
    lblMenuInicio: TLabel;
    imgMenuInicio: TImage;
    lblMenuAgenda: TLabel;
    imgMenuAgenda: TImage;
    lblMenuCarrinho: TLabel;
    imgMenuCarrinho: TImage;
    lblMenuPerfil: TLabel;
    imgMenuPerfil: TImage;
    scrollHome: TVertScrollBox;
    lytHeaderHome: TLayout;
    lblBemVindo: TLabel;
    lblNomeCliente: TLabel;
    lytAcoesHeader: TLayout;
    imgNotificacao: TImage;
    circlePerfil: TCircle;
    lytBusca: TLayout;
    rectFundoBusca: TRectangle;
    edtBusca: TEdit;
    rectBannerOferta: TRectangle;
    lblSubtituloOferta: TLabel;
    lblTituloOferta: TLabel;
    lytBtnOferta: TLayout;
    rectBtnAproveitar: TRectangle;
    lblAproveitar: TLabel;
    scrollCategorias: THorzScrollBox;
    rectFiltroTodos: TRectangle;
    lblFiltroTodos: TLabel;
    rectFiltroEstetica: TRectangle;
    lblFiltroEstetica: TLabel;
    rectFiltroCabelo: TRectangle;
    lblFiltroCabelo: TLabel;
    rectFiltroBarba: TRectangle;
    lblFiltroBarba: TLabel;
    lytTituloServicos: TLayout;
    lblTituloServicos: TLabel;
    lblVerTodos: TLabel;
    rectCardCorte: TRectangle;
    imgFotoCorte: TImage;
    lytInfoCorte: TLayout;
    lblNomeCorte: TLabel;
    lblDescCorte: TLabel;
    lblPrecoCorte: TLabel;
    rectBtnAddCorte: TRectangle;
    lblBtnAddCorte: TLabel;
    rectCardBarba: TRectangle;
    imgFotoBarba: TImage;
    lytInfoBarba: TLayout;
    lblNomeBarba: TLabel;
    lblDescBarba: TLabel;
    lblPrecoBarba: TLabel;
    rectBtnAddBarba: TRectangle;
    lblBtnAddBarba: TLabel;
    rectCardSobrancelha: TRectangle;
    imgFotoSobrancelha: TImage;
    lytInfoSobrancelha: TLayout;
    lblNomeSobrancelha: TLabel;
    lblDescSobrancelha: TLabel;
    lblPrecoSobrancelha: TLabel;
    rectBtnAddSobrancelha: TRectangle;
    lblBtnAddSobrancelha: TLabel;
    tabAgendamento: TTabItem;
    rectFundoAgendamento: TRectangle;
    rectRodapeConfirma: TRectangle;
    lytResumoValores: TLayout;
    lblResumoServico: TLabel;
    lblResumoData: TLabel;
    lblResumoBarbeiro: TLabel;
    lytResumoPreco: TLayout;
    lblTextoTotal: TLabel;
    lblValorTotal: TLabel;
    rectBtnConfirmar: TRectangle;
    lblBtnConfirmar: TLabel;
    scrollAgendamento: TVertScrollBox;
    lytHeaderAgendar: TLayout;
    rectBtnVoltarAgendar: TRectangle;
    lblIconeVoltarAgendar: TLabel;
    lytTextosHeader: TLayout;
    lblTituloAgendar: TLabel;
    lblSubTituloAgendar: TLabel;
    rectServicoAgendar: TRectangle;
    rectIconeServico: TRectangle;
    lytContainerBadge: TLayout;
    rectBadgeSelecionado: TRectangle;
    lblBadgeSelecionado: TLabel;
    lytInfoServicoAgendar: TLayout;
    lblNomeServicoAgendar: TLabel;
    lytDetalhesServico: TLayout;
    lblTempoServico: TLabel;
    lblPrecoServico: TLabel;
    lytMesAgendar: TLayout;
    lblMesAtual: TLabel;
    lytSetasMes: TLayout;
    rectSetaAnterior: TRectangle;
    lblIconeAnterior: TLabel;
    rectSetaProximo: TRectangle;
    lblIconeProximo: TLabel;
    scrollDatas: THorzScrollBox;
    rectDiaSabado: TRectangle;
    lblDiaSemanaSabado: TLabel;
    lblDiaNumeroSabado: TLabel;
    rectDiaDomingo: TRectangle;
    lblDiaSemanaDomingo: TLabel;
    lblDiaNumeroDomingo: TLabel;
    rectDiaSegunda: TRectangle;
    lblDiaSemanaSegunda: TLabel;
    lblDiaNumeroSegunda: TLabel;
    rectDiaTerca: TRectangle;
    lblDiaSemanaTerca: TLabel;
    lblDiaNumeroTerca: TLabel;
    rectDiaQuarta: TRectangle;
    lblDiaSemanaQuarta: TLabel;
    lblDiaNumeroQuarta: TLabel;
    rectDiaQuinta: TRectangle;
    lblDiaSemanaQuinta: TLabel;
    lblDiaNumeroQuinta: TLabel;
    rectDiaSexta: TRectangle;
    lblDiaSemanaSexta: TLabel;
    lblDiaNumeroSexta: TLabel;
    lytTituloHorarios: TLayout;
    lblHorariosDisponiveis: TLabel;
    lytLegendaCores: TLayout;
    lytLegendaDisp: TLayout;
    circleLegendaDisp: TCircle;
    lblLegendaDisp: TLabel;
    lytLegendaOcup: TLayout;
    circleLegendaOcup: TCircle;
    lblLegendaOcup: TLabel;
    flowHorarios: TFlowLayout;
    rectHora0900: TRectangle;
    lblHora0900: TLabel;
    rectHora0930: TRectangle;
    lblHora0930: TLabel;
    rectHora1000: TRectangle;
    lblHora1000: TLabel;
    rectHora1030: TRectangle;
    lblHora1030: TLabel;
    rectHora1100: TRectangle;
    lblHora1100: TLabel;
    rectHora1130: TRectangle;
    lblHora1130: TLabel;
    rectHora1200: TRectangle;
    lblHora1200: TLabel;
    rectHora1230: TRectangle;
    lblHora1230: TLabel;
    rectHora1300: TRectangle;
    lblHora1300: TLabel;
    rectHora1330: TRectangle;
    lblHora1330: TLabel;
    rectHora1400: TRectangle;
    lblHora1400: TLabel;
    rectHora1430: TRectangle;
    lblHora1430: TLabel;
    rectHora1500: TRectangle;
    lblHora1500: TLabel;
    rectHora1530: TRectangle;
    lblHora1530: TLabel;
    rectHora1600: TRectangle;
    lblHora1600: TLabel;
    rectHora1630: TRectangle;
    lblHora1630: TLabel;
    rectHora1700: TRectangle;
    lblHora1700: TLabel;
    rectHora1730: TRectangle;
    lblHora1730: TLabel;
    rectHora1800: TRectangle;
    lblHora1800: TLabel;
    rectHora1830: TRectangle;
    lblHora1830: TLabel;
    lblTituloBarbeiros: TLabel;
    rectBarbeiroPedro: TRectangle;
    Circle1: TCircle;
    Layout1: TLayout;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    procedure lblVoltarClick(Sender: TObject);
    procedure lblJaTenhoContaClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FrmPrincipal: TFrmPrincipal;

implementation

{$R *.fmx}

procedure TFrmPrincipal.lblJaTenhoContaClick(Sender: TObject);
begin
  TabControlPrincipal.GotoVisibleTab(0, TTabTransition.Slide, TTabTransitionDirection.Reversed);
end;

procedure TFrmPrincipal.lblVoltarClick(Sender: TObject);
begin
  TabControlPrincipal.GotoVisibleTab(0, TTabTransition.Slide);
end;

end.
