-- Migration 001: Adicionar coluna DT_CADASTRO a TB_USUARIOS
-- Base de dados: BARBERMANAGER.FDB (Firebird 3.0)
-- Ligacao: SYSDBA / masterkey / Protocol=Local

ALTER TABLE TB_USUARIOS ADD DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE TB_USUARIOS SET DT_CADASTRO = CURRENT_TIMESTAMP WHERE DT_CADASTRO IS NULL;
